/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_au_javacourse_tasks_lecture19_classwork_HelloWorldJNI */

#ifndef _Included_edu_au_javacourse_tasks_lecture19_classwork_HelloWorldJNI
#define _Included_edu_au_javacourse_tasks_lecture19_classwork_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_au_javacourse_tasks_lecture19_classwork_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_au_javacourse_tasks_lecture19_classwork_HelloWorldJNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
